### ISSUE TITLE
Four so important questions to better understand the SNUG?

### ISSUE THREAD

**Issue by opendeeple** [isantesteban/snug#14]
![photo_2022-06-15_14-50-41](https://user-images.githubusercontent.com/74002741/173798863-0f31db53-9572-4fef-aa7d-9f9caf91c6de.jpg)
### I have the questions about overview of SNUG (described on Figure 2 in your paper)?
1. Is there any pre-process that should be done, except getting the right poses dataset and splitting them into sub-sequences?
2. Were your pre-trained models trained with initial hidden states N(μ, σ)? If yes, why initial hidden states is 0 in run_snug.py?
3. On Garment Model, did you use any post-process after/before skinning while training? If yes, what is it? Because fig. 2 from paper states that training pipeline includes the post-process.
4. Why M(β, φ<sub>t-2</sub>) and M(β, φ<sub>t-1</sub>) is connected with inertia loss only, i.e not along with static losses too?

Thanks for your answers !!!

**Comment by Simonhfls** [comment]
Hi @opendeeple , do you have the answer to the third question?
I think there is no pre-process needed and the model is trained with random initial hidden states. For your last question, I think it's because only inertia loss is calculated based on 3 consecutive frames.
