### ISSUE TITLE
I want to know where is the demo

### ISSUE THREAD

**Issue by wtupdl** [isantesteban/snug#19]
Hello, I watched your demo video, I want to know where is the demo of your demo video

**Comment by dancasas** [comment]
The GUI is not released, but you are able to generate an output video given an input motion following the instructions described in the [README.md](https://github.com/isantesteban/snug/blob/main/README.md). Specifically, running this command: 

`python run_snug.py --motion assets/CMU/07/07_02_poses.npz --garment tshirt  --savedir tmp/07_02`

**Comment by wtupdl** [comment]
> 

ok，thank you

**Comment by wtupdl** [comment]
ok，thank you
