### ISSUE TITLE
Have you released the training code?

### ISSUE THREAD

**Issue by wtupdl** [isantesteban/snug#20]
Hello, I am researching self-supervised clothing training, can you please provide me with the training code? Or recommend other journal papers or training codes, if you can, thank you very much.

**Comment by dancasas** [comment]
We released an implementation of the losses here: https://github.com/isantesteban/snug#physics-based-losses. The full training code it is not released, but these losses should be sufficient to reproduce our training described in the paper.

**Comment by wtupdl** [comment]
ok，thank you
