### ISSUE TITLE
How do you map the joints of SMPL+H in CMU Data to SMPL joints

### ISSUE THREAD

**Issue by wsn1226** [isantesteban/snug#22]
I noticed that the SMPL+H CMU Mocap data contains 52 joints, but the SMPL model only contains 24 joints. I know the first 22 joints are the same, but how do you define the last two (left hand and right hand)?

**Comment by dancasas** [comment]
SMPL does not have hand joints (i.e., can't articulate the hands), hence you can just ignore them from the SMPL+H data. SNUG will only use the SMPL joints, you can see how motions are loaded here:

https://github.com/isantesteban/snug/blob/a99f7422bdbd2b5dea6f23a69f65f024b9202a1f/snug_utils.py#L69

**Comment by wsn1226** [comment]
I got it. Thank you so much for your information.
