### ISSUE TITLE
Is it possible to Unity as collision? 

### ISSUE THREAD

**Issue by TharHtetAungg** [isantesteban/snug#23]
Hello, I want to know about your output result can use it on Unity as garment collision ? Or does it need to do some work in order to use in Unity ? 

Thanks.

**Comment by dancasas** [comment]
The output meshes can be imported as `.obj` into Unity, sure. It's just a triangular mesh. Thanks!

**Comment by TharHtetAungg** [comment]
@dancasas But the output is too many obj sequences for one mesh which is not working on unity like that for mesh collision.
