### ISSUE TITLE
Which sequences are the test ones?

### ISSUE THREAD

**Issue by yigals** [isantesteban/snug#5]
In the paper you mention using 52 sequences from the AMASS dataset, 4 of which are left for testing - which ones are they?
Thanks!

**Comment by isantesteban** [comment]
Hi! You can find the full list of sequences in this repository: https://github.com/isantesteban/vto-dataset#sequences
From that list, these are the ones we use for testing: ```01_01```, ```07_02```, ```104_54```, ```55_27```

Some of the original sequences were too long/repetitive so we have cut some of them to avoid having redundant data. You can get the exact sequences by downloading this dataset: https://github.com/isantesteban/vto-dataset/tree/main/tshirt/simulations

(To train SNUG we don't use the simulation data, just the sequences of body poses)

Hope this helps!

**Comment by yigals** [comment]
And just to clarify, they were the test sequences for each of the models in the repo, right?

**Comment by isantesteban** [comment]
Yes, that's correct
