### ISSUE TITLE
Prediction artifacts

### ISSUE THREAD

**Issue by yigals** [isantesteban/snug#6]
Hi,
I ran the tshirt, top, tank models on some of the sequences, both test and train, and noticed a few "shaking" artifacts in some of the sequences. Do you have any idea what could be their cause? 
The artifacts are consistent across gender and body shape.

I didn't see any shaking artifacts with tank model so presumably it has something to do with distance to body. But I would love to hear your take on that :)

test:
01_01 top f

https://user-images.githubusercontent.com/8408769/167576815-7593e054-c2e8-47df-856b-a3ba534231de.mp4

01_01 tshirt m

https://user-images.githubusercontent.com/8408769/167577036-30c692e2-0a6e-4889-bd18-8ee05cf614af.mp4

01_01 tank f

https://user-images.githubusercontent.com/8408769/167577118-6cbfd7c4-4e1d-439d-b1bb-f048f24869bf.mp4

some train seq, different body shapes:

https://user-images.githubusercontent.com/8408769/167577561-41a03c60-a5cb-4168-90f4-b425c16dcca6.mp4

https://user-images.githubusercontent.com/8408769/167577566-fed52ccf-89ff-4966-9445-abde31a65628.mp4

https://user-images.githubusercontent.com/8408769/167577567-cdbd96ca-6b62-421e-9bab-338751d033bd.mp4

https://user-images.githubusercontent.com/8408769/167577896-89fa66d8-868a-4805-aaac-fa043dbe5719.mp4

**Comment by isantesteban** [comment]
Hi! When I run the following command

`python run_snug.py --motion assets/CMU/01/01_01_poses.npz --garment top  --savedir tmp/01_01`

This is what I get:

https://user-images.githubusercontent.com/17111347/167582813-c833d945-766b-4656-b91b-948c8edcfbea.mp4

Are you using the same SMPL model as described in the [instructions](https://github.com/isantesteban/snug#download-human-model)? It seems that there are big collisions with the body and the collision postprocess is struggling to fix them. The garment models that we have uploaded only work for the female SMPL model

**Comment by yigals** [comment]
looks much better than my results, I will try following the instructions again and update. In the meantime, I don't see explicit collision post processing (or any post processing) in the prediction code, is it part of the tf model? the model definition is not available in the code

**Comment by yigals** [comment]
running with a pristine checkout on both linux and windows unfortunately produces these artifacts. could it be that it's because I'm missing explicit collision post processing?

https://user-images.githubusercontent.com/8408769/167615386-ce63c393-f3bf-4793-a805-05f561258676.mp4

**Comment by isantesteban** [comment]
Hi, the collision post processing is included in the models. I'm trying to reproduce your issues but I need more information. What version of tensorflow are you using? Are you running on CPU or GPU? 

Also, could you check the checksum of the SMPL model file?
```
$md5sum assets/SMPL/basicModel_f_lbs_10_207_0_v1.0.0.pkl
0842c0f9b87d95730fb0e5048f05d611  basicModel_f_lbs_10_207_0_v1.0.0.pkl
```

**Comment by yigals** [comment]
Thanks for helping :D

If collision post-processing is included in the models then how are there any collisions in the videos I uploaded (first pose)?
I'm running on GPU - RTX 3080. Currently on a windows machine, but it's the same in a fedora machine.

```
>python -c "import tensorflow; print(tensorflow.__version__)"
2.7.0

>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:15:10_Pacific_Standard_Time_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0


>grep "define CUDNN_MAJOR" -A 2 "%CUDA_PATH%\include\cudnn_version.h"
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 1
#define CUDNN_PATCHLEVEL 0

>md5sum assets/SMPL/basicModel_f_lbs_10_207_0_v1.0.0.pkl
0842c0f9b87d95730fb0e5048f05d611 *assets/SMPL/basicModel_f_lbs_10_207_0_v1.0.0.pkl

```

**Comment by yigals** [comment]
Hi @isantesteban, any update re license? :)
currently the code has no license, meaning it can't be used at all

**Comment by isantesteban** [comment]
Sorry, no updates yet!

We are looking into using a similar license as [TailorNet](https://github.com/chaitanya100100/TailorNet/blob/master/LICENSE.md) to allow using our code for research purposes, but I'm still waiting for the approval

**Comment by isantesteban** [comment]
Hi again, sorry for the delay. We have uploaded the license of the code
